/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//definición de variables
uint8_t dummy_8bit = 0;
uint16_t dummy_16bit = 0;
uint32_t dummy_32bit = 0;
uint8_t daniel_8 = 0;

uint16_t dummy_16bit_dec = 0;
uint16_t dummy_16bit_bin = 0;
uint16_t dummy_16bit_hex = 0;


static void delay(volatile uint32_t count)
{

	while (count--){

		__NOP();
	}
}

int main(void)
{
	dummy_8bit = 123;
	dummy_16bit = 4986;
	dummy_32bit = 12345678;

	dummy_16bit_dec = 32;
	dummy_16bit_bin = 0x20;
	dummy_16bit_hex = 0b100000;

	//cargando el valor de xxxx en la variable
	//dummy_16bit_bin = dummy_16bit_bin >>

	daniel_8 = 735;
	//LO PRIMERO QUE SE HACE ES ACTIVAR LA SEÑAL DE RELOJ,
	//DEPENDIENDO DEL PUERTO EN EL QUE ESTEMOS TRABAJANDO
	//NECESITAMOS PONER LA POSICIÓN DONDE ESTA EL PUERTO QUE TRABAJAREMOS


	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; //Ya encendimos la señal de reloj

	//PODEMOS REDEFINIR EL NOMBRE
	//reiniciar registro
	GPIOA->MODER &= ~GPIO_MODER_MODER5; //limpie el registro
	GPIOA->MODER |= GPIO_MODER_MODE5_0;

	GPIOA->OTYPER &= ~GPIO_OTYPER_OT5;

	GPIOA->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR5;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5_1;

	//(GPIOx_PUPDR)
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPD5;
	//GPIOA->PUPDR |= GPIO_PUPDR_PUPD5_1;

	//GPIOA->ODR &= ~GPIO_ODR_OD5;




	while(1){
		GPIOA->ODR |= GPIO_ODR_OD5;
		delay(500000);
	}
	return 0;


}
